openapi: 3.0.0
info:
  title: Library API with JWT Authentication
  version: 1.0.0
  description: Demo JWT + Swagger for book library

servers:
  - url: http://localhost:3000

paths:
  /login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              example:
                username: admin
                password: 123456
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: List of books

  /books/{id}:
    get:
      summary: Get a single book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A book object
        '404':
          description: Book not found

  /profile:
    get:
      summary: Access protected route
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile
        '401':
          description: Unauthorized

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
