openapi: 3.0.3
info:
  title: Books API
  version: "1.0.0"
  description: API quản lý sách (theo Flask-Smorest)
servers:
  - url: http://localhost:5000
paths:
  /api/v1/books:
    get:
      summary: Lấy danh sách sách
      responses:
        "200":
          description: Danh sách sách
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      summary: Thêm sách mới
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookInput"
      responses:
        "201":
          description: Sách được tạo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
  /api/v1/books/{book_id}:
    get:
      summary: Lấy chi tiết 1 cuốn sách
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Thông tin sách
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "404":
          description: Không tìm thấy sách
    put:
      summary: Cập nhật thông tin sách
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookInput"
      responses:
        "200":
          description: Sách được cập nhật
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
        "404":
          description: Không tìm thấy sách
    delete:
      summary: Xóa sách
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Sách bị xóa
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
    BookInput:
      type: object
      required:
        - title
        - author
      properties:
        title:
          type: string
        author:
          type: string
